CREATE DATABASE webs DEFAULT CHARACTER SET utf8;
USE webs;

CREATE TABLE news (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	title VARCHAR(128) NOT NULL,
	content TEXT NULL,
	cr_date DATE,
	authorID SMALLINT UNSIGNED NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY (authorID) REFERENCES authors (id) ON UPDATE CASCADE ON DELETE CASCADE,
	UNIQUE KEY(title)
) ENGINE = InnoDB;
CREATE TABLE authors (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	Sname VARCHAR(30) NOT NULL,
	Fname VARCHAR(30) NOT NULL,
	Pname VARCHAR(50) ,
	profession VARCHAR(255),
	Narticle INT NULL CHECK (Narticle >=0),
	PRIMARY KEY(id)
) ENGINE = InnoDB;
CREATE TABLE categories(
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	describing TEXT,
	PRIMARY KEY(id),
	UNIQUE KEY (name)
) ENGINE = InnoDB;
CREATE TABLE resources(
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL UNIQUE,
	Tres VARCHAR(255),
	link TEXT NOT NULL,
		PRIMARY KEY(id),
		UNIQUE KEY (name)
)ENGINE = InnoDB;
CREATE TABLE news_categories(
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	category_nID SMALLINT UNSIGNED NOT NULL,
	newsID SMALLINT UNSIGNED NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY (category_nID) REFERENCES categories (id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (newsID) REFERENCES news (id) ON UPDATE CASCADE ON DELETE CASCADE,
	UNIQUE KEY (category_nID,newsID)
) ENGINE = InnoDB;
